# Generated by Django 4.1.6 on 2023-02-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('ano', models.IntegerField(max_length=100)),
                ('recomendacao', models.IntegerField(max_length=100)),
                ('estudio', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=500)),
            ],
        ),
    ]
